### PR TITLE
66 fix multi cluster envs

### LINKED ISSUE #66: Fix issues with multi cluster environments
/kind bug

**What happened**:

Multi cluster environments are currently failing on AWS 

**What you expected to happen**:

A multi cluster environment comes with a hub and n cluster. Currently generated terraform code is not able to properly create clusters

### PR DESCRIPTION
**Pull request by dippynark**
**What this PR does / why we need it**: Multi cluster environements currently do not work with Tarmak. This PR fixes this by tagging subnets and instances appropriately so that clusters can function properly

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #66 

**Special notes for your reviewer**:

**Release note**:

```release-note
Fix multi cluster environments by supporting multiple clusters in a single VPC
```

### CODE REVIEW

File: terraform/Dockerfile [hunk 1]
```diff
@@ -15,6 +15,17 @@ RUN curl -sL  https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terr
...
+
+ENV TERRAFORM_PROVIDER_AWSTAG_VERSION 0.1
+ENV TERRAFORM_PROVIDER_AWSTAG_HASH f2f1a153637f837ab521a4f1d0e236e08927354610495a199e4f67985de28a83
+RUN curl -sL https://github.com/dippynark/terraform-provider-awstag/releases/download/release-${TERRAFORM_PROVIDER_AWSTAG_VERSION}/terraform-provider-awstag_linux_amd64.zip > /tmp/terraform-provider-awstag.zip && \
+    sha256sum /tmp/terraform-provider-awstag.zip && \
+    echo "${TERRAFORM_PROVIDER_AWSTAG_HASH}  /tmp/terraform-provider-awstag.zip" | sha256sum -c && \
+    unzip /tmp/terraform-provider-awstag.zip && \
+    rm /tmp/terraform-provider-awstag.zip && \
+    mv terraform-provider-awstag /terraform/terraform-provider-awstag && \
+    chmod +x /terraform/terraform-provider-awstag
```
Comment (simonswine) [inline terraform/Dockerfile]: Before we can merge this we need to verify the binary using GPG. I think it would make sense to use airworthy and verify both our custom awstag provider and the terraform binary. 

https://github.com/jetstack/airworthy

File: pkg/terraform/providers/awstag/resource_awstag_ec2_tag.go [hunk 2]
```diff
@@ -0,0 +1,188 @@
...
+
+	_, err := conn.DeleteTags(req)
+	if err != nil {
+		return fmt.Errorf("Error deleting tag: %s", err)
+	}
+
+	return nil
+}
+
+/*func resourceAwstagEC2TagUpdate(d *schema.ResourceData, meta interface{}) error {
```
Comment (simonswine) [inline pkg/terraform/providers/awstag/resource_awstag_ec2_tag.go]: Can we get rid of this comment

**Comment by simonswine** [comment]
@dippynark can you take a look at my comments. Again also the verify boilterplate is failing because we don't have the LICENSE headers in the newly added files

File: terraform/Dockerfile [hunk 3]
```diff
@@ -3,11 +3,17 @@ FROM alpine:3.6
...
+
 # install terraform
 ENV TERRAFORM_VERSION 0.10.8
-ENV TERRAFORM_HASH b786c0cf936e24145fad632efd0fe48c831558cc9e43c071fffd93f35e3150db
-RUN curl -sL  https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip > /tmp/terraform.zip && \
-    echo "${TERRAFORM_HASH}  /tmp/terraform.zip" | sha256sum  -c && \
+RUN curl -sL  https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip > terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
+    airworthy -v download https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS -S https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS.sig && \
+    cat terraform_${TERRAFORM_VERSION}_SHA256SUMS | grep terraform_${TERRAFORM_VERSION}_linux_amd64.zip > terraform_${TERRAFORM_VERSION}_linux_amd64_SHA256SUMS && \
+    sha256sum -c terraform_${TERRAFORM_VERSION}_linux_amd64_SHA256SUMS && \
```
Comment (simonswine) [inline terraform/Dockerfile]: There is no need for this, airworthy is checking the sha256 sum already

File: terraform/Dockerfile [hunk 4]
```diff
@@ -3,11 +3,17 @@ FROM alpine:3.6
 
 RUN apk add --no-cache unzip curl
 
+# install airworthy
+COPY airworthy /usr/local/bin/airworthy
```
Comment (simonswine) [inline terraform/Dockerfile]: Airworthy should be download from github releases page and sha256sum check performed on it

See here: https://github.com/jetstack/tarmak/blob/master/terraform/amazon/kubernetes/templates/puppet_agent_user_data.yaml#L15
