### PR TITLE
Only converge on wing when not in infrastructure only

### LINKED ISSUE #475: Don't wait for wing to converge when running apply with --infrastructure only
**What happened**:
I ran `tarmak clusters apply --infrastructure-only` on a cluster where wing was still running, my apply command waited for wing to complete.

**What you expected to happen**:
I expected to not have to wait for wing. I'd viewed this just as a kind of terraform only flag and expected it to complete when terraform was done.

**How to reproduce it (as minimally and precisely as possible)**:
Use the `--infrastructure-only` flag on an apply operation while wing is still running.

**Environment**: 
- Kubernetes version (use `kubectl version`): 1.10
- Tarmak: 0.5 alpha 2

In `pkg/tarmak/terraform.go` we have some logic that looks a bit like this:

```go
func (t *Tarmak) CmdTerraformApply(args []string, ctx context.Context) error {
...
	t.cluster.Log().Info("running apply")
	// run terraform apply always, do not run it when in configuration only mode
	if !t.flags.Cluster.Apply.ConfigurationOnly {
		err := t.terraform.Apply(t.Cluster())
	}

	// upload tar gz only if terraform hasn't uploaded it yet
	if t.flags.Cluster.Apply.ConfigurationOnly {
		err := t.Cluster().UploadConfiguration()
	}

	// reapply config expect if we are in infrastructure only
	if !t.flags.Cluster.Apply.InfrastructureOnly {
		err := t.Cluster().ReapplyConfiguration()
	}

	// wait for convergance in every mode  <----------- Are we sure we want this?
	err := t.Cluster().WaitForConvergance()
}
```

I propose that when doing an InfrastructureOnly apply, we should skip waiting for convergence. Perhaps there's something I'm missing. What do people think?

### PR DESCRIPTION
**Pull request by JoshVanL**
**What this PR does / why we need it**:
Don't wait for wing to converge when we're not in infrastructure only

fixes #475

```release-note
Don't wait for wing conversion when we're not in infrastructure only
```

### CODE REVIEW

**Comment by simonswine** [comment]
Can you look at this together with our notes from the tarmak call last week:

- Add `--wait-for-convergence=true` flag that can be enabled
- If plan doesn't not change anything don't wait for convergance (this is blocked by #531)

**Comment by MattiasGees** [comment]
Nothing changed, only rebase

/lgtm
/approve

File: pkg/tarmak/cmd.go [hunk 1]
```diff
@@ -82,10 +84,12 @@ func (c *CmdTarmak) Apply() error {
 	default:
 	}
 
-	// wait for convergance in every mode
-	err := c.Cluster().WaitForConvergance()
-	if err != nil {
-		return err
+	// wait for convergance if flag enabled and has changed
+	if hasChanged && c.flags.Cluster.Apply.WaitForConvergence {
```
Comment (simonswine) [inline pkg/tarmak/cmd.go]: We need to wait for convergance when we update the config through the tarmak update method  (and not terraform) in ConfigurationOnly 

We update the puppet tar config and send out a converge request. The only way to skip that would if we would know if the config has changed through our upload method in tarmak (puppet.tar.gz is the same).

When we update the puppet.tar.gz in the default mode we have a terraform change for updating the puppet.tar.gz

**Comment by simonswine** [comment]
I don't think that handles `cluster apply -C` correctly. I think in those cases it needs to be waiting for convergence as the configuration might have changed. (see my code commit)

/assign @JoshVanL 
/unassign

**Comment by simonswine** [comment]
Thank you that seems to work

/approve
/lgtm
